version: "3"

services:
  web:
    image: ghost
    environment:
      url: https://ghost.test.localhost

  http:
    image: pathwae/pathwae
    environment:
      CONFIG: |
        ghost.test.localhost:
          to: http://web:2368
          force_ssl: true
    ports:
      - 80:80
      - 443:443

