version: "3"

services:
  web:
    image: ghost
    environment:
      url: https://blog.test.localhost

  http:
    image: quay.io/pathwae/proxy
    volumes:
      - ./certs:/certs:ro,z
    environment:
      CONFIG: |
        blog.test.localhost:
          to: http://web:2368
          force_ssl: true
    ports:
      - 80:80
      - 443:443
      - 8080:8080

